workspace:
  base: /go
  path: src/github.com/jmccann/drone-github-comment

pipeline:
  test:
    image: golang:1.8
    commands:
      - go test -cover

  build:
    when:
      local: false
    image: plugins/docker:17.05
    repo: jmccann/drone-github-comment
